package com.argocd.platform.api.model.response.argocd;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;
import java.util.Map;

/**
 * Response returned by the ArgoCD ApplicationSet Plugin Generator endpoint.
 *
 * <p>ArgoCD requires the shape {@code {output: {parameters: [{key: value, ...}, ...]}}}.
 * Each entry in {@code parameters} becomes one Application generated by the ApplicationSet.
 *
 * <p>Values may be strings, integers, booleans, arrays, or nested objects — the ArgoCD
 * Plugin Generator protocol (v2.6+) supports native JSON types. Arrays are available in
 * the Helm chart via {@code range} without needing {@code fromJson}.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PluginGeneratorResponse {

    private Output output;

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class Output {
        /**
         * Each entry generates one Application. Keys become template variables
         * available as {@code {{key}}} in the ApplicationSet template block.
         * Array and object values are passed as native JSON — Helm receives them
         * as structured values that can be used with {@code range} directly.
         */
        private List<Map<String, Object>> parameters;
    }
}
