apiVersion: v1
kind: Secret
metadata:
  name: cp-1
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
    argocd-platform/control-plane: "true"
type: Opaque
stringData:
  name: cp-1
  server: https://cp-1-control-plane:6443
  config: |
    {
      "bearerToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjduMUQwTUNCMFlFRkpwUWt5cWdjbVRkVEVEUHJRWlhMMVp3TlBNbVF4VHMifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzg2Nzk5OTYyLCJpYXQiOjE3ODY3OTYzNjIsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwianRpIjoiOWVkNGYxNmItMWQ1NS00ZjBjLTk3ODctNTEzNTdkYmE1YTBlIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsInNlcnZpY2VhY2NvdW50Ijp7Im5hbWUiOiJhcmdvY2QtbWFuYWdlciIsInVpZCI6IjY2YTUzYWZiLTlkMzEtNDRlNy1iZWI2LWJjNzczMDc4YjI5MCJ9fSwibmJmIjoxNzg2Nzk2MzYyLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06YXJnb2NkLW1hbmFnZXIifQ.Wr3_6s3jgthHXV3NJXlpG8KjFIQ0YN10-6U-KMZ6DluSjH6buvfu76LewGwXyRo-f_-rerCSKMlT5nx_eJsAUuVZF-zuWymsqZurS-mo6t_c8BucYHErXf4POIYG85FbwVZQrkn16OEl94d-sn6TF-i3K83XiFfMPmiTMInwkSMPZCqeDscUpdgbviLLT99ZFU3P9M8DHDsrM3ntTzS2gZVTjWGQiB5pqipfEnvUiTZkbmofUke0nBoOSUSne3QY1HIbJh3k2GNVzMsRHs2K0chdAzX1ioA1M8Zuhum603KphKKs5gQ3Zw83peB-5vABxS6cLfTG_jzfHnhKz9mGMQ",
      "tlsClientConfig": {
        "insecure": true
      }
    }