apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: control-planes
  namespace: argocd

spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd-platform/control-plane: "true"

  template:
    metadata:
      name: 'argocd-{{nameNormalized}}'

    spec:
      project: default

      sources:
        - repoURL: https://argoproj.github.io/argo-helm
          chart: argo-cd
          targetRevision: 10.3.3
          helm:
            valueFiles:
              - $values/control-planes/values/default.yaml
              - $values/control-planes/values/{{name}}/default.yaml

        - repoURL: https://github.com/hemant0308/argocd-platform.git
          targetRevision: main
          ref: values

      destination:
        server: '{{server}}'
        namespace: argocd

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true